"""add live_events table

Revision ID: c60843ca4355
Revises: g4c5d6e7f8a9
Create Date: 2026-06-14 21:42:13.437723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60843ca4355'
down_revision: Union[str, Sequence[str], None] = 'g4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('offset_seconds', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('user_nickname', sa.String(length=255), nullable=False),
    sa.Column('user_unique_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('gift_name', sa.String(length=255), nullable=True),
    sa.Column('gift_diamond_count', sa.Integer(), nullable=True),
    sa.Column('gift_repeat_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_events_id'), 'live_events', ['id'], unique=False)
    op.create_index(op.f('ix_live_events_recording_id'), 'live_events', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_events_recording_id'), table_name='live_events')
    op.drop_index(op.f('ix_live_events_id'), table_name='live_events')
    op.drop_table('live_events')
    # ### end Alembic commands ###
