"""add thumbnail_ready to recordings

Revision ID: h6a7b8c9d0e1
Revises: c60843ca4355
Create Date: 2026-06-23 01:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'h6a7b8c9d0e1'
down_revision: Union[str, Sequence[str], None] = 'c60843ca4355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('thumbnail_ready', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'thumbnail_ready')
    # ### end Alembic commands ###
